name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run typecheck
      - run: bun run format:check
      - run: bun run lint
      - run: bun run test:unit
      - run: bun run test:types
      - run: bun run test:cypress:component
      - run: bun run test:cypress:e2e
